# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger: none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'd590edaf-e44a-4607-9161-e5b10c2c08c3'

  # Function app name
  functionAppName: '23savageintellect-function-app'

  # Environment name
  environmentName: 'learn'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_Deploy
  displayName: Build and Deploy Stage
  jobs:
  - job: Build_Deploy
    displayName: Build and Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'
      - script: |
          cd si-ui/
          npm install -g @angular/cli
          npm install
          ng build --prod
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'
      - task: AzureCLI@1
        displayName: Az File Copy to Storage
        inputs:
          azureSubscription: $(azureSubscription)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch \
              --destination \$web \
              --account-name "23savageintellectui" \
              --source "si-ui/www"
      # - task: ArchiveFiles@2
      #   displayName: 'Archive files'
      #   inputs:
      #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/si-ui/www/'
      #     includeRootFolder: false
      #     archiveType: zip
      #     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      #     replaceExistingArchive: true
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      #     ArtifactName: 'drop'
      #     publishLocation: 'Container'
# - stage: Deploy
#   displayName: Deploy stage
#   jobs:
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: $(vmImageName)
#     steps:
      # - task: ExtractFiles@1
      #   displayName: 'Extract files '
      #   inputs:
      #     archiveFilePatterns: '**/$(Build.BuildId).zip'
      #     destinationFolder: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)'
      # - task: AzureFileCopy@4
      #   displayName: 'Copy Files to Storage'
      #   inputs:
      #     azureSubscription: 'd590edaf-e44a-4607-9161-e5b10c2c08c3'
      #     SourcePath: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)/*'
      #     Destination: 'AzureBlob'
      #     storage: '23savageintellectui'
      #     ContainerName: '$web'
      # - script: |
      #     pwd
      #     ls -a
      #     cd si-ui
      #     ls -a
      #   displayName: 'npm install and build'
      #   workingDirectory: '$(Build.SourcesDirectory)'

      # - task: AzureCLI@1
      #   displayName: Az File Copy to Storage
      #   inputs:
      #     azureSubscription: $(azureSubscription)
      #     scriptLocation: inlineScript
      #     inlineScript: |
      #       az storage blob upload-batch \
      #         --destination \$web \
      #         --account-name "23savageintellectui" \
      #         --source "$(System.DefaultWorkingDirectory)/si-ui/www/*"
      #az storage blob upload-batch --destination $web --account-name "23savageintellectui" --source "/"